<?php

namespace App\Helpers;

use App\Models\Tag;

class InterestTagData
{
    public static function getTransformedInterestCoreArray()
    {
        $transformed = [];
        $toTransformArray = self::getToTransformInterestCoreArray();

        foreach($toTransformArray as $toTransformCore) {
            foreach ($toTransformCore['data'] as $vertical) {
                $transformed[trim($vertical)][] = $toTransformCore['key'];
            }
        }

        return $transformed;
    }

    public static function getToTransformInterestCoreArray()
    {
        return [
            [
                'key' => 'Activewear',
                'data' => [
                    'athletic',
                    'athletics',
                    'sports and fitness',
                    'sport',
                    'sport health',
                    'sporter',
                    'sports',
                    'gymer',
                    'yoga',
                    'adventure',
                    'surf',
                ],
            ],
            [
                'key' => 'Anime & Cosplay',
                'data' => [
                    'cosplay',
                    'animation',
                ],
            ],
            [
                'key' => 'Art & Design',
                'data' => [
                    'arts',
                    'animation',
                    'art',
                    'painting',
                    'interior design',
                    'interiors',
                    'design',
                    'creative',
                    'art',
                    'arts',
                    'creative',
                    'design',
                    'diy',
                    'graphic',
                    'interiors',
                    'interior design',
                    'visuals',
                    'painting',
                    'diy',
                    'graphic',
                    'visuals',
                ],
            ],
            [
                'key' => 'Beauty & Cosmetics',
                'data' => [
                    'beautiful',
                    'beauty',
                    'beauty fashion',
                    'korean beauty',
                    'make up',
                    'make up tutorial',
                    'makeup',
                    'biolage matrix.',
                    'pageant',
                    'beauty',
                    'beauty lifestyle fashion',
                    'beauty\/fashtion',
                    'beauty | fashion | lifestyle',
                    'beauty. fashion',
                    'beauty\/lifestyle',
                    'beauty\r\nlifestyle',
                    'cosmetic',
                    'makeup',
                    'beauty fashion',
                    'beauty\/fashion',
                    'beauty\/parenting',
                    'biolage matrix.',
                    'fashion | beauty | lifestyle',
                    'fashion\/beauty',
                    'lifestyle | beauty | fashion',
                    'lifestyle | travel | beauty',
                    'make up',
                    'lifestyle | beauty',
                    'beauty | fashion | lifestyle',
                    'beauty lifestyle fashion',
                    'beauty. fashion',
                    'beauty\/fashion',
                    'beauty\/fashtion',
                    'beauty\/lifestyle',
                    'beauty\/model',
                    'beauty\/parenting',
                    'beauty\r\nfashion',
                    'beauty\r\nlifestyle',
                    'cosmetic',
                    'fashion | beauty | lifestyle',
                    'fashion\/beauty',
                    'lifestyle | beauty',
                    'lifestyle | beauty | fashion',
                    'lifestyle | beauty | youtube personality',
                    'lifestyle | travel | beauty',
                ],
            ],
            [
                'key' => 'Beer, Wine & Spirits',
                'data' => [
                ],
            ],
            [
                'key' => 'Business, Finance & Careers',
                'data' => [
                    'business',
                    'investment',
                    'entrepreneurship',
                    'business & education',
                    'business',
                    'business & education',
                    'investment',
                    'financial (2)',
                    'economics',
                    'career',
                    'career',
                    'economics',
                    'finance',
                ],
            ],
            [
                'key' => 'Camera & Photography',
                'data' => [
                    'photography',
                    'videographer',
                    'street',
                    'sports\r\ntravel\r\nphotographer',
                    'videography',
                    'photography',
                    'street',
                    'sports\r\ntravel\r\nphotographer',
                    'videography',
                ],
            ],
            [
                'key' => 'Cars & Motorbikes',
                'data' => [
                    'automobil',
                    'automobile',
                    'automotive',
                    'car',
                    'cars',
                    'otomototif',
                    'motor',
                    'motosports',
                    'automotive',
                    'automobil',
                    'automobile',
                    'car',
                    'motor',
                    'otomototif',
                    'otomotive',
                    'motosports',
                    'otomotive',
                ],
            ],
            [
                'key' => 'Charity & Social Cause',
                'data' => [
                    'social & culture website',
                    'social enterprise',
                    'charity',
                    'social enterprise',
                    'environment (6)',
                    'activist (2)',
                    'activist\r\nenvironment',
                    'activist',
                    'conservation',
                    'movement',
                    'environment',
                    'positivity (1)',
                    'positivity',
                    'activist',
                    'activist\r\nenvironment',
                    'conservation',
                    'environment',
                    'movement',
                    'positivity',
                ],
            ],
            [
                'key' => 'Clothes, Shoes, Handbags & Accessories',
                'data' => [
                    'style',
                    'shopping',
                    'shoes and fashion',
                    'fashion',
                    'fashion instagram',
                    'fashion lifestyle',
                    'menswear',
                    'artiste | lifestyle | fashion',
                    'beauty lifestyle fashion',
                    'beauty\/fashtion',
                    'menswear',
                    'fsahion',
                    'beauty | fashion | lifestyle',
                    'beauty. fashion',
                    'beauty\/lifestyle',
                    'beauty\r\nlifestyle',
                    'beauty fashion',
                    'beauty\/fashion',
                    'fashion lifestyle',
                    'fashion\/parenting',
                    'fashion | beauty | lifestyle',
                    'fashion\/beauty',
                    'fashion. lifestyle',
                    'fashion',
                    'shoes',
                    'sneakers',
                    'style',
                    'lifestyle | beauty | fashion',
                    'shopping',
                    'shoes and fashion',
                    'muslimah fashion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | fashion',
                    'artiste | lifestyle | fashion',
                    'beauty | fashion | lifestyle',
                    'beauty lifestyle fashion',
                    'beauty. fashion',
                    'beauty\/fashion',
                    'beauty\/fashtion',
                    'beauty\r\nfashion',
                    'fashion | beauty | lifestyle',
                    'fashion. lifestyle',
                    'fashion\/beauty',
                    'fashion\/parenting',
                    'fashion\/parenting\/actress',
                    'fsahion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | beauty | fashion',
                    'lifestyle | fashion',
                    'music. fashion',
                    'muslimah fashion',
                    'shoes',
                    'sneakers',
                ],
            ],
            [
                'key' => 'Coffee, Tea & Beverages',
                'data' => [
                ],
            ],
            [
                'key' => 'Dance',
                'data' => [
                    'performing arts',
                    'dance',
                    'aerial arts',
                    'performing arts',
                    'aerial arts',
                ],
            ],
            [
                'key' => 'Electronics & Computers',
                'data' => [
                    'technology',
                    'tech review',
                    'tech',
                    'digital lifestyle',
                    'tech',
                    'technology',
                    'digital',
                    'digital lifestyle',
                    'tech review',
                    'digital',
                ],
            ],
            [
                'key' => 'Fitness & Yoga',
                'data' => [
                    'athletic',
                    'athletics',
                    'sports and fitness',
                    'sport',
                    'sport health',
                    'sporter',
                    'sports',
                    'health',
                    'health & fitness',
                    'health and fitness',
                    'fitness',
                    'wellness',
                    'gymer',
                    'body show',
                    'martial art',
                    'yoga',
                    'adventure',
                    'surf',
                    'athletic',
                    'basketball',
                    'health & fitness',
                    'health and fitness',
                    'gym\/lifestyle',
                    'health',
                    'healthy',
                    'football',
                    'fitness',
                    'lifestyle | fitness',
                    'sports and fitness',
                    'surf',
                    'yoga',
                    'gym\/lifestyle',
                    'gym\/ actor\/ model \/mc',
                    'healthy',
                    'lifestyle | fitness',
                ],
            ],
            [
                'key' => 'Friends, Family & Relationships',
                'data' => [
                    'parent',
                    'parenthood',
                    'mommy',
                    'moms',
                    'daddy',
                    'family',
                    'youth',
                    'parenting',
                    'kid influencer',
                    'familiy',
                    'family',
                    'daddy',
                    'mommy',
                    'moms',
                    'mom',
                    'mom kols',
                    'moms parenting',
                    'family. style',
                    'young',
                    'young generation',
                    'youth',
                    'parenthood',
                    'parenting\r\nparent\r\nfamily',
                    'teen',
                    'kid influencer',
                    'marriage',
                    'relationship',
                    'relationship (1)',
                    'dating (6)',
                    'love (3)',
                    'parenting',
                    'parent',
                    'kids\/familiy',
                    'dating',
                    'parenting lifestyle',
                    'couple',
                    'hot mom',
                    'love',
                    'twins',
                    'friend',
                    'couple',
                    'dating',
                    'familiy',
                    'family. style',
                    'fashion\/parenting',
                    'fashion\/parenting\/actress',
                    'friend',
                    'hot mom',
                    'kids\/familiy',
                    'love',
                    'marriage',
                    'mom',
                    'mom kols',
                    'moms parenting',
                    'parenting lifestyle',
                    'parenting\r\nparent\r\nfamily',
                    'relationship',
                    'teen',
                    'twins',
                    'young generation',
                ],
            ],
            [
                'key' => 'Gaming',
                'data' => [
                    'game',
                    'games',
                    'gaming',
                    'gammer',
                    'chess',
                    'fifa',
                    'games',
                    'game',
                    'chess',
                    'esports',
                    'rov - Gaming',
                    'esports',
                    'rov',
                ],
            ],
            [
                'key' => 'Healthcare & Medicine',
                'data' => [
                    'medical',
                    'medicine',
                    'surgery',
                ],
            ],
            [
                'key' => 'Healthy Lifestyle',
                'data' => [
                    'athletic',
                    'athletics',
                    'sports and fitness',
                    'sport',
                    'sport health',
                    'sporter',
                    'sports',
                    'health',
                    'health & fitness',
                    'health and fitness',
                    'fitness',
                    'wellness',
                    'gymer',
                    'body show',
                    'martial art',
                    'yoga',
                    'adventure',
                    'surf',
                    'athletic',
                    'basketball',
                    'health & fitness',
                    'health and fitness',
                    'gym\/lifestyle',
                    'health',
                    'healthy',
                    'fitness',
                    'lifestyle | fitness',
                    'sports and fitness',
                    'surf',
                    'wellness',
                    'healthy',
                    'lifestyle | fitness',
                    'swimming',
                ],
            ],
            [
                'key' => 'Home Decor, Furniture & Garden',
                'data' => [
                    'home',
                    'urban',
                    'urban living',
                    'urban (5)',
                    'urban living (2)',
                    'home (5)',
                    'home',
                    'urban',
                    'urban living',
                ],
            ],
            [
                'key' => 'Jewellery & Watches',
                'data' => [
                    'style',
                    'shopping',
                    'artiste | lifestyle | fashion',
                    'beauty lifestyle fashion',
                    'beauty\/fashtion',
                    'fsahion',
                    'beauty | fashion | lifestyle',
                    'beauty. fashion',
                    'beauty\/lifestyle',
                    'beauty\r\nlifestyle',
                    'beauty fashion',
                    'beauty\/fashion',
                    'fashion lifestyle',
                    'fashion\/parenting',
                    'fashion | beauty | lifestyle',
                    'fashion\/beauty',
                    'fashion. lifestyle',
                    'fashion',
                    'style',
                    'lifestyle | beauty | fashion',
                    'shopping',
                    'shoes and fashion',
                    'muslimah fashion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | fashion',
                    'artiste | lifestyle | fashion',
                    'beauty | fashion | lifestyle',
                    'beauty lifestyle fashion',
                    'beauty. fashion',
                    'beauty\/fashion',
                    'beauty\/fashtion',
                    'beauty\r\nfashion',
                    'fashion | beauty | lifestyle',
                    'fashion. lifestyle',
                    'fashion\/beauty',
                    'fashion\/parenting',
                    'fashion\/parenting\/actress',
                    'fsahion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | beauty | fashion',
                    'lifestyle | fashion',
                    'music. fashion',
                    'muslimah fashion',
                ],
            ],
            [
                'key' => 'Luxury Goods',
                'data' => [
                    'style',
                    'shopping',
                    'artiste | lifestyle | fashion',
                    'beauty lifestyle fashion',
                    'beauty\/fashtion',
                    'fsahion',
                    'beauty | fashion | lifestyle',
                    'beauty. fashion',
                    'beauty\/lifestyle',
                    'beauty\r\nlifestyle',
                    'beauty fashion',
                    'beauty\/fashion',
                    'fashion lifestyle',
                    'fashion\/parenting',
                    'fashion | beauty | lifestyle',
                    'fashion\/beauty',
                    'fashion. lifestyle',
                    'fashion',
                    'style',
                    'lifestyle | beauty | fashion',
                    'shopping',
                    'shoes and fashion',
                    'muslimah fashion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | fashion',
                    'artiste | lifestyle | fashion',
                    'beauty | fashion | lifestyle',
                    'beauty lifestyle fashion',
                    'beauty. fashion',
                    'beauty\/fashion',
                    'beauty\/fashtion',
                    'beauty\r\nfashion',
                    'fashion | beauty | lifestyle',
                    'fashion. lifestyle',
                    'fashion\/beauty',
                    'fashion\/parenting',
                    'fashion\/parenting\/actress',
                    'fsahion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | beauty | fashion',
                    'lifestyle | fashion',
                    'music. fashion',
                    'muslimah fashion',
                ],
            ],
            [
                'key' => 'Music',
                'data' => [
                    'band',
                    'country music',
                    'music',
                    'music',
                    'cover',
                    'hiphop',
                    'k-pop',
                    'country music',
                    'music. fashion',
                    'kpop',
                    'hiphop',
                    'k-pop',
                    'music (beatbox)',
                    'music (beatbox)',
                    'music. fashion',
                    'singing',
                ],
            ],
            [
                'key' => 'Pets',
                'data' => [
                    'animal',
                    'animal loves',
                    'pet',
                    'pets',
                    'animal loves',
                    'animal',
                    'pet',
                    'pets',
                    'dog',
                    'dog',
                ],
            ],
            [
                'key' => 'Pop Culture & Entertainment',
                'data' => [
                    'culture',
                    'comedy',
                    'studio',
                    'entertainment',
                    'tarot',
                    'parodies',
                    'movie',
                    'viner',
                    'humor',
                    'lifestyle entertainment',
                    'magic',
                    'promotion',
                    'online advertising talent',
                    'vj',
                    'edutainment',
                    'lifestyle entertainment',
                    'magic',
                    'lifestyle entertainment',
                    'mid (5)',
                    'lifestyle cartoon (4)',
                    'lifestyle (2572)',
                    'party (3)',
                    'lifestyle cartoon',
                    'culture',
                    'tarot',
                    'studio',
                    'mid',
                    'lifestyle cartoon',
                    'mid',
                    'party',
                    'stand up comedy',
                ],
            ],
            [
                'key' => 'Restaurants, Food & Grocery',
                'data' => [
                    'restaurateur',
                    'pastry',
                    'pastry chef',
                    'food',
                    'cosplay food',
                    'cooking',
                    'culinary',
                    'food lover',
                    'food stylish',
                    'food instagram',
                    'application',
                    'cosplay food',
                    'food lover',
                    'pastry',
                    'organic',
                    'organic',
                ],
            ],
            [
                'key' => 'Science or Education',
                'data' => [
                    'education',
                    'edutainment',
                    'business & education',
                    'college',
                    'education',
                    'college',
                ],
            ],
            [
                'key' => 'Shopping & Retail',
                'data' => [
                    'style',
                    'shoppin',
                    'shoes and fashio',
                    'fashio',
                    'fashion instagra',
                    'fashion lifestyl',
                    'menswea',
                    'artiste | lifestyle | fashion',
                    'beauty lifestyle fashion',
                    'beauty\/fashtion',
                    'beauty\/fashtion',
                    'menswear',
                    'fsahion',
                    'beauty | fashion | lifestyle',
                    'beauty. fashion',
                    'beauty\/lifestyle',
                    'beauty\r\nlifestyle',
                    'beauty fashion',
                    'beauty\/fashion',
                    'fashion lifestyle',
                    'fashion\/parenting',
                    'fashion | beauty | lifestyle',
                    'fashion\/beauty',
                    'fashion. lifestyle',
                    'fashion',
                    'style',
                    'lifestyle | beauty | fashion',
                    'shopping',
                    'shoes and fashion',
                    'muslimah fashion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | fashion',
                    'artiste | lifestyle | fashion',
                    'beauty | fashion | lifestyle',
                    'beauty lifestyle fashion',
                    'beauty. fashion',
                    'beauty\/fashion',
                    'beauty\/fashtion',
                    'beauty\r\nfashion',
                    'fashion | beauty | lifestyle',
                    'fashion. lifestyle',
                    'fashion\/beauty',
                    'fashion\/parenting',
                    'fashion\/parenting\/actress',
                    'fsahion',
                    'hijab fashion',
                    'hijabi fashion',
                    'lifestyle | beauty | fashion',
                    'lifestyle | fashion',
                    'music. fashion',
                    'muslimah fashion',
                    'shoes',
                    'sneakers',
                ],
            ],
            [
                'key' => 'Sports',
                'data' => [
                    'athletic',
                    'athletics',
                    'sports and fitness',
                    'sport',
                    'sport health',
                    'sporter',
                    'sports',
                    'basketball',
                    'tennis',
                    'fifa',
                    'football',
                    'cycling',
                    'body show',
                    'martial art',
                    'adventure',
                    'surf',
                    'health & fitness',
                    'health and fitness',
                    'gym\/lifestyle',
                    'health',
                    'healthy',
                    'fitness',
                    'lifestyle | fitness',
                    'sports\r\ntravel\r\nphotographer',
                    'martial art',
                    'sports',
                    'sports and fitness',
                    'sport',
                    'surf',
                    'tennis',
                    'energetic girl',
                    'cycling',
                    'lifestyle | fitness',
                    'swimming',
                ],
            ],
            [
                'key' => 'Television & Film',
                'data' => [
                    'television studio',
                    'tv producer',
                    'tv host',
                    'hos',
                    'media',
                    'news',
                    'network',
                    'net idol',
                    'news beauty',
                    'newspaper',
                    'radio',
                    'talk show',
                    'online newspaper',
                    'magazine',
                    'net idol',
                    'documentary',
                    'film',
                    'tv commercial',
                    'tv program',
                ],
            ],
            [
                'key' => 'Toys, Children & Baby',
                'data' => [
                    'baby',
                    'kid',
                    'parent',
                    'parenthood',
                    'mommy',
                    'moms',
                    'daddy',
                    'family',
                    'child',
                    'toys',
                    'parenting',
                    'kid influencer',
                    'kids',
                    'young',
                    'children',
                    'baby',
                    'child',
                    'familiy',
                    'family',
                    'daddy',
                    'mommy',
                    'moms',
                    'mom',
                    'mom kols',
                    'moms parenting',
                    'family. style',
                    'young',
                    'young generation',
                    'youth',
                    'parenthood',
                    'parenting\r\nparent\r\nfamily',
                    'teen',
                    'kid influencer',
                    'toys',
                    'parenting',
                    'parent',
                    'kid',
                    'kids\/familiy',
                    'kids',
                    'twins',
                    'children',
                    'kids\/familiy',
                ],
            ],
            [
                'key' => 'Travel, Tourism & Aviation',
                'data' => [
                    'travel',
                    'travel and lifestyle',
                    'travel instagram',
                    'travel show',
                    'travels',
                    'tourism',
                    'nature',
                    'and travel',
                    'adventure',
                    'artiste | lifestyle | travel',
                    'sports\r\ntravel\r\nphotographer',
                    'lifestyle | travel | beauty',
                    'tourist',
                    'travel show',
                    'nature',
                    'travel',
                    'travel and lifestyle',
                    'language',
                    'and travel',
                    'artiste | lifestyle | travel',
                    'language',
                    'lifestyle | travel | beauty',
                    'sports\r\ntravel\r\nphotographer',
                ],
            ],
            [
                'key' => 'Wedding',
                'data' => [
                ],
            ],
        ];
    }
}