<?php

namespace App\Helpers;

class ProfessionTagData
{
    public static function getVerticalToProfessionCore()
    {
        return [
            'actor' => self::getVerticalToProfessionCoreActor(),
            'actress' => self::getVerticalToProfessionCoreActor(),
            'artist' => self::getVerticalToProfessionCoreActor(),
            'artiste' => self::getVerticalToProfessionCoreActor(),
            'malaysian actress' => self::getVerticalToProfessionCoreActor(),
            'tv actor' => self::getVerticalToProfessionCoreActor(),
            'women actor' => self::getVerticalToProfessionCoreActor(),
            'actress\/model\/singer' => self::getVerticalToProfessionCoreActor(),
            'actress \/mc\/parenting' => self::getVerticalToProfessionCoreActor(),
            'actor\/actress' => self::getVerticalToProfessionCoreActor(),
            'actor parenting' => self::getVerticalToProfessionCoreActor(),
            'actor\/celeb' => self::getVerticalToProfessionCoreActor(),
            'actor\/gym' => self::getVerticalToProfessionCoreActor(),
            'actress\r\nmodel' => self::getVerticalToProfessionCoreActor(),
            'actress\/parenting' => self::getVerticalToProfessionCoreActor(),
            'celebrity | actor' => self::getVerticalToProfessionCoreActor(),
            'actress\/parenting' => self::getVerticalToProfessionCoreActor(),
            'actor parenting' => self::getVerticalToProfessionCoreActor(),
            'actor' => self::getVerticalToProfessionCoreActor(),
            'artiste' => self::getVerticalToProfessionCoreActor(),
            'actor\/celeb' => self::getVerticalToProfessionCoreActor(),
            'celebrity | actor' => self::getVerticalToProfessionCoreActor(),
            'tv actor' => self::getVerticalToProfessionCoreActor(),
            'actor\/gym' => self::getVerticalToProfessionCoreActor(),
            'actress' => self::getVerticalToProfessionCoreActor(),
            'malaysian actress' => self::getVerticalToProfessionCoreActor(),
            'actor\/actress' => self::getVerticalToProfessionCoreActor(),
            'actress \/mc\/parenting' => self::getVerticalToProfessionCoreActor(),
            'actress\/model\/singer' => self::getVerticalToProfessionCoreActor(),
            'actress\r\nmodel' => self::getVerticalToProfessionCoreActor(),
            'women actor' => self::getVerticalToProfessionCoreActor(),
            'acting' => self::getVerticalToProfessionCoreActor(),

            'art director' => self::getVerticalToProfessionCoreArtist(),
            'calligrapher' => self::getVerticalToProfessionCoreArtist(),
            'dancer' => self::getVerticalToProfessionCoreArtist(),
            'painter' => self::getVerticalToProfessionCoreArtist(),
            'creative director' => self::getVerticalToProfessionCoreArtist(),
            'artists' => self::getVerticalToProfessionCoreArtist(),
            'artists' => self::getVerticalToProfessionCoreArtist(),
            'poet' => self::getVerticalToProfessionCoreArtist(),
            'ballerina' => self::getVerticalToProfessionCoreArtist(),
            'poet' => self::getVerticalToProfessionCoreArtist(),
            'dancer' => self::getVerticalToProfessionCoreArtist(),
            'classical pianist' => self::getVerticalToProfessionCoreArtist(),
            'creative director' => self::getVerticalToProfessionCoreArtist(),
            'artists' => self::getVerticalToProfessionCoreArtist(),
            'painter' => self::getVerticalToProfessionCoreArtist(),
            'artist' => self::getVerticalToProfessionCoreArtist(),

            'athlete' => self::getVerticalToProfessionCoreAthelte(),
            'ballerina' => self::getVerticalToProfessionCoreAthelte(),
            'football player' => self::getVerticalToProfessionCoreAthelte(),
            'footballer' => self::getVerticalToProfessionCoreAthelte(),
            'biker' => self::getVerticalToProfessionCoreAthelte(),
            'motorcycle racer' => self::getVerticalToProfessionCoreAthelte(),
            'national athlete' => self::getVerticalToProfessionCoreAthelte(),
            'personal trainer' => self::getVerticalToProfessionCoreAthelte(),
            'professional football player' => self::getVerticalToProfessionCoreAthelte(),
            'racer' => self::getVerticalToProfessionCoreAthelte(),
            'racing' => self::getVerticalToProfessionCoreAthelte(),
            'skater' => self::getVerticalToProfessionCoreAthelte(),
            'swimming' => self::getVerticalToProfessionCoreAthelte(),
            'yoga instructor' => self::getVerticalToProfessionCoreAthelte(),
            'bmx talent' => self::getVerticalToProfessionCoreAthelte(),
            'athelete' => self::getVerticalToProfessionCoreAthelte(),
            'gym\/ actor\/ model \/mc' => self::getVerticalToProfessionCoreAthelte(),
            'gymer' => self::getVerticalToProfessionCoreAthelte(),
            'health & fitness enthusiast' => self::getVerticalToProfessionCoreAthelte(),
            'sporter' => self::getVerticalToProfessionCoreAthelte(),
            'sport health' => self::getVerticalToProfessionCoreAthelte(),
            'skater' => self::getVerticalToProfessionCoreAthelte(),
            'motorcycle racer' => self::getVerticalToProfessionCoreAthelte(),
            'yoga instructor' => self::getVerticalToProfessionCoreAthelte(),
            'fitness model' => self::getVerticalToProfessionCoreAthelte(),
            'bmx talent' => self::getVerticalToProfessionCoreAthelte(),
            'professional football player' => self::getVerticalToProfessionCoreAthelte(),
            'biker' => self::getVerticalToProfessionCoreAthelte(),
            'health & fitness enthusiast' => self::getVerticalToProfessionCoreAthelte(),
            'athelete' => self::getVerticalToProfessionCoreAthelte(),
            'football player' => self::getVerticalToProfessionCoreAthelte(),
            'sport host' => self::getVerticalToProfessionCoreAthelte(),
            'footballer' => self::getVerticalToProfessionCoreAthelte(),
            'energetic girl' => self::getVerticalToProfessionCoreAthelte(),
            'national athlete' => self::getVerticalToProfessionCoreAthelte(),
            'racer' => self::getVerticalToProfessionCoreAthelte(),
            'athlete' => self::getVerticalToProfessionCoreAthelte(),
            'racing' => self::getVerticalToProfessionCoreAthelte(),

            'beautician' => self::getVerticalToProfessionCoreBeauty(),
            'beauty reviewer' => self::getVerticalToProfessionCoreBeauty(),
            'grooming instructor' => self::getVerticalToProfessionCoreBeauty(),
            'make up artist' => self::getVerticalToProfessionCoreBeauty(),
            'makeup artist' => self::getVerticalToProfessionCoreBeauty(),
            'mua' => self::getVerticalToProfessionCoreBeauty(),
            'stylist' => self::getVerticalToProfessionCoreBeauty(),
            'fashionista' => self::getVerticalToProfessionCoreBeauty(),
            'fashion instagram' => self::getVerticalToProfessionCoreBeauty(),
            'beauty\/model' => self::getVerticalToProfessionCoreBeauty(),
            'fashion\/parenting\/actress' => self::getVerticalToProfessionCoreBeauty(),
            'make up tutorial' => self::getVerticalToProfessionCoreBeauty(),
            'news beauty' => self::getVerticalToProfessionCoreBeauty(),
            'beauty\/actress' => self::getVerticalToProfessionCoreBeauty(),
            'hair designer' => self::getVerticalToProfessionCoreBeauty(),
            'korean beauty' => self::getVerticalToProfessionCoreBeauty(),
            'youtubers beauty' => self::getVerticalToProfessionCoreBeauty(),
            'beauty reviewer' => self::getVerticalToProfessionCoreBeauty(),
            'beauty blogger' => self::getVerticalToProfessionCoreBeauty(),
            'fashionista' => self::getVerticalToProfessionCoreBeauty(),
            'mua' => self::getVerticalToProfessionCoreBeauty(),
            'youtubers beauty' => self::getVerticalToProfessionCoreBeauty(),
            'stylist' => self::getVerticalToProfessionCoreBeauty(),
            'hair designer' => self::getVerticalToProfessionCoreBeauty(),
            'make up artist' => self::getVerticalToProfessionCoreBeauty(),
            'beautician' => self::getVerticalToProfessionCoreBeauty(),
            'grooming instructor' => self::getVerticalToProfessionCoreBeauty(),
            'beauty\/actress' => self::getVerticalToProfessionCoreBeauty(),
            'makeup artist' => self::getVerticalToProfessionCoreBeauty(),

            'businessman' => self::getVerticalToProfessionCoreBusinessFinance(),
            'enterpreneur' => self::getVerticalToProfessionCoreBusinessFinance(),
            'entrepreneur' => self::getVerticalToProfessionCoreBusinessFinance(),
            'finance' => self::getVerticalToProfessionCoreBusinessFinance(),
            'financial service' => self::getVerticalToProfessionCoreBusinessFinance(),

            'b-vlogger' => self::getVerticalToProfessionCoreContentCreator(),
            'beauty bloger' => self::getVerticalToProfessionCoreContentCreator(),
            'beauty blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'food blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'influencer' => self::getVerticalToProfessionCoreContentCreator(),
            'content creator' => self::getVerticalToProfessionCoreContentCreator(),
            'content producer' => self::getVerticalToProfessionCoreContentCreator(),
            'creator' => self::getVerticalToProfessionCoreContentCreator(),
            'influencers' => self::getVerticalToProfessionCoreContentCreator(),
            'streamer' => self::getVerticalToProfessionCoreContentCreator(),
            'streaming' => self::getVerticalToProfessionCoreContentCreator(),
            'tech blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'travel blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'vblogger' => self::getVerticalToProfessionCoreContentCreator(),
            'viner' => self::getVerticalToProfessionCoreContentCreator(),
            'vlogger' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'youtuber' => self::getVerticalToProfessionCoreContentCreator(),
            'youtubers' => self::getVerticalToProfessionCoreContentCreator(),
            'blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'blogging' => self::getVerticalToProfessionCoreContentCreator(),
            'reviewer' => self::getVerticalToProfessionCoreContentCreator(),
            'yt personality' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube channel' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube personalities' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube personality' => self::getVerticalToProfessionCoreContentCreator(),
            'yt channel' => self::getVerticalToProfessionCoreContentCreator(),
            'television studio' => self::getVerticalToProfessionCoreContentCreator(),
            'social & culture website' => self::getVerticalToProfessionCoreContentCreator(),
            'web tv network' => self::getVerticalToProfessionCoreContentCreator(),
            'instagram' => self::getVerticalToProfessionCoreContentCreator(),
            'application' => self::getVerticalToProfessionCoreContentCreator(),
            'media website' => self::getVerticalToProfessionCoreContentCreator(),
            'network' => self::getVerticalToProfessionCoreContentCreator(),
            'website' => self::getVerticalToProfessionCoreContentCreator(),
            'blog' => self::getVerticalToProfessionCoreContentCreator(),
            'vlog' => self::getVerticalToProfessionCoreContentCreator(),
            'forum' => self::getVerticalToProfessionCoreContentCreator(),
            'content creature' => self::getVerticalToProfessionCoreContentCreator(),
            'entertain page' => self::getVerticalToProfessionCoreContentCreator(),
            'facebook' => self::getVerticalToProfessionCoreContentCreator(),
            'family blogger' => self::getVerticalToProfessionCoreContentCreator(),
            'foorball page' => self::getVerticalToProfessionCoreContentCreator(),
            'football page' => self::getVerticalToProfessionCoreContentCreator(),
            'kol astrology - Content Creator' => self::getVerticalToProfessionCoreContentCreator(),
            'lifestyle | beauty | youtube personality' => self::getVerticalToProfessionCoreContentCreator(),
            'live stream' => self::getVerticalToProfessionCoreContentCreator(),
            'livestream' => self::getVerticalToProfessionCoreContentCreator(),
            'media' => self::getVerticalToProfessionCoreContentCreator(),
            'media page' => self::getVerticalToProfessionCoreContentCreator(),
            'media page\r\nenvironment' => self::getVerticalToProfessionCoreContentCreator(),
            'page' => self::getVerticalToProfessionCoreContentCreator(),
            'personality' => self::getVerticalToProfessionCoreContentCreator(),
            'review' => self::getVerticalToProfessionCoreContentCreator(),
            'ribbit' => self::getVerticalToProfessionCoreContentCreator(),
            'social page' => self::getVerticalToProfessionCoreContentCreator(),
            'tiktok' => self::getVerticalToProfessionCoreContentCreator(),
            'tiktoker' => self::getVerticalToProfessionCoreContentCreator(),
            'video' => self::getVerticalToProfessionCoreContentCreator(),
            'vlogs' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube channel (39)' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube personalities (2)' => self::getVerticalToProfessionCoreContentCreator(),
            'youtube personality (6)' => self::getVerticalToProfessionCoreContentCreator(),
            'youtubers duo (1)' => self::getVerticalToProfessionCoreContentCreator(),
            'yt channel (53)' => self::getVerticalToProfessionCoreContentCreator(),

            'designer' => self::getVerticalToProfessionCoreDesign(),
            'architect' => self::getVerticalToProfessionCoreDesign(),
            'fashion designer' => self::getVerticalToProfessionCoreDesign(),
            'graphic designer' => self::getVerticalToProfessionCoreDesign(),
            'interior designer' => self::getVerticalToProfessionCoreDesign(),
            'designer\/parenting' => self::getVerticalToProfessionCoreDesign(),
            'illustrator' => self::getVerticalToProfessionCoreDesign(),
            'fashion designer' => self::getVerticalToProfessionCoreDesign(),
            'art director' => self::getVerticalToProfessionCoreDesign(),
            'calligrapher' => self::getVerticalToProfessionCoreDesign(),
            'graphic designer' => self::getVerticalToProfessionCoreDesign(),
            'interior designer' => self::getVerticalToProfessionCoreDesign(),
            'architect' => self::getVerticalToProfessionCoreDesign(),
            'designer' => self::getVerticalToProfessionCoreDesign(),
            'designer\/parenting' => self::getVerticalToProfessionCoreDesign(),
            'illustrator' => self::getVerticalToProfessionCoreDesign(),

            'director' => self::getVerticalToProfessionCoreDirectorProducer(),
            'documentary' => self::getVerticalToProfessionCoreDirectorProducer(),
            'executive producer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'film' => self::getVerticalToProfessionCoreDirectorProducer(),
            'film director' => self::getVerticalToProfessionCoreDirectorProducer(),
            'film producer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'filmmaker' => self::getVerticalToProfessionCoreDirectorProducer(),
            'movie director' => self::getVerticalToProfessionCoreDirectorProducer(),
            'producer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'script writer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'scriptwriter' => self::getVerticalToProfessionCoreDirectorProducer(),
            'tv producer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'production company' => self::getVerticalToProfessionCoreDirectorProducer(),
            'acting' => self::getVerticalToProfessionCoreDirectorProducer(),
            'movie' => self::getVerticalToProfessionCoreDirectorProducer(),
            'cinematographer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'script writer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'filmmaker' => self::getVerticalToProfessionCoreDirectorProducer(),
            'movie director' => self::getVerticalToProfessionCoreDirectorProducer(),
            'director' => self::getVerticalToProfessionCoreDirectorProducer(),
            'cinematographer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'executive producer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'producer' => self::getVerticalToProfessionCoreDirectorProducer(),
            'scriptwriter' => self::getVerticalToProfessionCoreDirectorProducer(),
            'film producer' => self::getVerticalToProfessionCoreDirectorProducer(),

            'comedian' => self::getVerticalToProfessionCoreEntertainer(),
            'commentator' => self::getVerticalToProfessionCoreEntertainer(),
            'entertainer' => self::getVerticalToProfessionCoreEntertainer(),
            'host' => self::getVerticalToProfessionCoreEntertainer(),
            'host tv show' => self::getVerticalToProfessionCoreEntertainer(),
            'magician' => self::getVerticalToProfessionCoreEntertainer(),
            'mc' => self::getVerticalToProfessionCoreEntertainer(),
            'announcer' => self::getVerticalToProfessionCoreEntertainer(),
            'moderator' => self::getVerticalToProfessionCoreEntertainer(),
            'presenter' => self::getVerticalToProfessionCoreEntertainer(),
            'radio & tv host' => self::getVerticalToProfessionCoreEntertainer(),
            'radio announcer' => self::getVerticalToProfessionCoreEntertainer(),
            'radio dj' => self::getVerticalToProfessionCoreEntertainer(),
            'radio host' => self::getVerticalToProfessionCoreEntertainer(),
            'speaker' => self::getVerticalToProfessionCoreEntertainer(),
            'sport host' => self::getVerticalToProfessionCoreEntertainer(),
            'television host' => self::getVerticalToProfessionCoreEntertainer(),
            'travel tv host' => self::getVerticalToProfessionCoreEntertainer(),
            'traveling tv host' => self::getVerticalToProfessionCoreEntertainer(),
            'tv host' => self::getVerticalToProfessionCoreEntertainer(),
            'tv personality' => self::getVerticalToProfessionCoreEntertainer(),
            'tv presenter' => self::getVerticalToProfessionCoreEntertainer(),
            'vj' => self::getVerticalToProfessionCoreEntertainer(),
            'emcee' => self::getVerticalToProfessionCoreEntertainer(),
            'entertainment' => self::getVerticalToProfessionCoreEntertainer(),
            'events' => self::getVerticalToProfessionCoreEntertainer(),
            'vo' => self::getVerticalToProfessionCoreEntertainer(),
            'mc\/actress\/beauty\/pianist' => self::getVerticalToProfessionCoreEntertainer(),
            'hos' => self::getVerticalToProfessionCoreEntertainer(),
            'talk show' => self::getVerticalToProfessionCoreEntertainer(),
            'humor' => self::getVerticalToProfessionCoreEntertainer(),
            'comedy' => self::getVerticalToProfessionCoreEntertainer(),
            'party' => self::getVerticalToProfessionCoreEntertainer(),
            'comic page' => self::getVerticalToProfessionCoreEntertainer(),
            'hosting' => self::getVerticalToProfessionCoreEntertainer(),
            'online advertising talent' => self::getVerticalToProfessionCoreEntertainer(),
            'parodies' => self::getVerticalToProfessionCoreEntertainer(),
            'promotion' => self::getVerticalToProfessionCoreEntertainer(),
            'public figure' => self::getVerticalToProfessionCoreEntertainer(),
            'radio' => self::getVerticalToProfessionCoreEntertainer(),
            'anchor' => self::getVerticalToProfessionCoreEntertainer(),
            'news' => self::getVerticalToProfessionCoreEntertainer(),
            'news caster' => self::getVerticalToProfessionCoreEntertainer(),
            'stage host' => self::getVerticalToProfessionCoreEntertainer(),
            'stand up comedian' => self::getVerticalToProfessionCoreEntertainer(),
            'stand up comedy' => self::getVerticalToProfessionCoreEntertainer(),
            'tv program' => self::getVerticalToProfessionCoreEntertainer(),
            'public figure (2)' => self::getVerticalToProfessionCoreEntertainer(),
            'figure (3)' => self::getVerticalToProfessionCoreEntertainer(),
            'tv commercial' => self::getVerticalToProfessionCoreEntertainer(),
            'socialite' => self::getVerticalToProfessionCoreEntertainer(),
            'announcer' => self::getVerticalToProfessionCoreEntertainer(),
            'moderator' => self::getVerticalToProfessionCoreEntertainer(),
            'host' => self::getVerticalToProfessionCoreEntertainer(),
            'speaker' => self::getVerticalToProfessionCoreEntertainer(),
            'radio host' => self::getVerticalToProfessionCoreEntertainer(),
            'production company' => self::getVerticalToProfessionCoreEntertainer(),
            'magician' => self::getVerticalToProfessionCoreEntertainer(),
            'host tv show' => self::getVerticalToProfessionCoreEntertainer(),
            'comedian' => self::getVerticalToProfessionCoreEntertainer(),
            'presenter' => self::getVerticalToProfessionCoreEntertainer(),
            'tv personality' => self::getVerticalToProfessionCoreEntertainer(),
            'mc' => self::getVerticalToProfessionCoreEntertainer(),
            'entertainer' => self::getVerticalToProfessionCoreEntertainer(),
            'commentator' => self::getVerticalToProfessionCoreEntertainer(),
            'emcee' => self::getVerticalToProfessionCoreEntertainer(),
            'radio dj' => self::getVerticalToProfessionCoreEntertainer(),
            'radio & tv host' => self::getVerticalToProfessionCoreEntertainer(),
            'anchor' => self::getVerticalToProfessionCoreEntertainer(),
            'radio announcer' => self::getVerticalToProfessionCoreEntertainer(),
            'stage host' => self::getVerticalToProfessionCoreEntertainer(),
            'stand up comedian' => self::getVerticalToProfessionCoreEntertainer(),
            'comic page' => self::getVerticalToProfessionCoreEntertainer(),
            'events' => self::getVerticalToProfessionCoreEntertainer(),
            'hosting' => self::getVerticalToProfessionCoreEntertainer(),
            'mc\/actress\/beauty\/pianist' => self::getVerticalToProfessionCoreEntertainer(),
            'personality' => self::getVerticalToProfessionCoreEntertainer(),
            'television host' => self::getVerticalToProfessionCoreEntertainer(),
            'tv presenter' => self::getVerticalToProfessionCoreEntertainer(),

            'baker' => self::getVerticalToProfessionCoreFoodBeverage(),
            'cake designer' => self::getVerticalToProfessionCoreFoodBeverage(),
            'celebrity chef' => self::getVerticalToProfessionCoreFoodBeverage(),
            'chef' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food reviewer' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food stylish' => self::getVerticalToProfessionCoreFoodBeverage(),
            'pastry chef' => self::getVerticalToProfessionCoreFoodBeverage(),
            'tv chef' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food instagram' => self::getVerticalToProfessionCoreFoodBeverage(),
            'lifestyle\/food reviewer' => self::getVerticalToProfessionCoreFoodBeverage(),
            'restaurateur' => self::getVerticalToProfessionCoreFoodBeverage(),
            'cooking' => self::getVerticalToProfessionCoreFoodBeverage(),
            'culinary' => self::getVerticalToProfessionCoreFoodBeverage(),
            'barista' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food review' => self::getVerticalToProfessionCoreFoodBeverage(),
            'foodie' => self::getVerticalToProfessionCoreFoodBeverage(),
            'foodies' => self::getVerticalToProfessionCoreFoodBeverage(),
            'cake designer' => self::getVerticalToProfessionCoreFoodBeverage(),
            'foodie' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food reviewer' => self::getVerticalToProfessionCoreFoodBeverage(),
            'baker' => self::getVerticalToProfessionCoreFoodBeverage(),
            'chef' => self::getVerticalToProfessionCoreFoodBeverage(),
            'tv chef' => self::getVerticalToProfessionCoreFoodBeverage(),
            'barista' => self::getVerticalToProfessionCoreFoodBeverage(),
            'food review' => self::getVerticalToProfessionCoreFoodBeverage(),
            'foodies' => self::getVerticalToProfessionCoreFoodBeverage(),
            'lifestyle\/food reviewer' => self::getVerticalToProfessionCoreFoodBeverage(),

            'game reviewer' => self::getVerticalToProfessionCoreGamer(),
            'gamer' => self::getVerticalToProfessionCoreGamer(),
            'gamers' => self::getVerticalToProfessionCoreGamer(),
            'online gamer' => self::getVerticalToProfessionCoreGamer(),
            'gaming' => self::getVerticalToProfessionCoreGamer(),
            'gamers | youtuber' => self::getVerticalToProfessionCoreGamer(),
            'gammer' => self::getVerticalToProfessionCoreGamer(),
            'game reviewer' => self::getVerticalToProfessionCoreGamer(),
            'gamer' => self::getVerticalToProfessionCoreGamer(),
            'gamers | youtuber' => self::getVerticalToProfessionCoreGamer(),
            'gamers' => self::getVerticalToProfessionCoreGamer(),
            'online gamer' => self::getVerticalToProfessionCoreGamer(),

            'fitness model' => self::getVerticalToProfessionCoreModel(),
            'model' => self::getVerticalToProfessionCoreModel(),
            'figure' => self::getVerticalToProfessionCoreModel(),
            'hot girl' => self::getVerticalToProfessionCoreModel(),
            'body show' => self::getVerticalToProfessionCoreModel(),
            'beautiful' => self::getVerticalToProfessionCoreModel(),
            'fitness model' => self::getVerticalToProfessionCoreModel(),
            'hot girl' => self::getVerticalToProfessionCoreModel(),
            'model' => self::getVerticalToProfessionCoreModel(),
            'model\/mc' => self::getVerticalToProfessionCoreModel(),

            'classical pianist' => self::getVerticalToProfessionCoreMusician(),
            'dj' => self::getVerticalToProfessionCoreMusician(),
            'music band' => self::getVerticalToProfessionCoreMusician(),
            'music dj' => self::getVerticalToProfessionCoreMusician(),
            'music producer' => self::getVerticalToProfessionCoreMusician(),
            'music singer' => self::getVerticalToProfessionCoreMusician(),
            'music singer band' => self::getVerticalToProfessionCoreMusician(),
            'musician' => self::getVerticalToProfessionCoreMusician(),
            'pianist' => self::getVerticalToProfessionCoreMusician(),
            'rapper' => self::getVerticalToProfessionCoreMusician(),
            'singer' => self::getVerticalToProfessionCoreMusician(),
            'singer music' => self::getVerticalToProfessionCoreMusician(),
            'singers' => self::getVerticalToProfessionCoreMusician(),
            'singing' => self::getVerticalToProfessionCoreMusician(),
            'song writer' => self::getVerticalToProfessionCoreMusician(),
            'song-writer' => self::getVerticalToProfessionCoreMusician(),
            'songwriter' => self::getVerticalToProfessionCoreMusician(),
            'voice trainer' => self::getVerticalToProfessionCoreMusician(),
            'music' => self::getVerticalToProfessionCoreMusician(),
            'singer\/artist' => self::getVerticalToProfessionCoreMusician(),
            'rapper\/music' => self::getVerticalToProfessionCoreMusician(),
            'singer\/song writer' => self::getVerticalToProfessionCoreMusician(),
            'singer\/songwriter\/actor' => self::getVerticalToProfessionCoreMusician(),
            'singer\/business' => self::getVerticalToProfessionCoreMusician(),
            'singer\/song-writer' => self::getVerticalToProfessionCoreMusician(),
            'singer\/parenting' => self::getVerticalToProfessionCoreMusician(),
            'band' => self::getVerticalToProfessionCoreMusician(),
            'cover' => self::getVerticalToProfessionCoreMusician(),
            'singer \r\nactress' => self::getVerticalToProfessionCoreMusician(),
            'rapper' => self::getVerticalToProfessionCoreMusician(),
            'singer\/song writer' => self::getVerticalToProfessionCoreMusician(),
            'musician' => self::getVerticalToProfessionCoreMusician(),
            'singer\/song-writer' => self::getVerticalToProfessionCoreMusician(),
            'singer music' => self::getVerticalToProfessionCoreMusician(),
            'songwriter' => self::getVerticalToProfessionCoreMusician(),
            'music producer' => self::getVerticalToProfessionCoreMusician(),
            'song writer' => self::getVerticalToProfessionCoreMusician(),
            'singer' => self::getVerticalToProfessionCoreMusician(),
            'music singer band' => self::getVerticalToProfessionCoreMusician(),
            'singer \r\nactress' => self::getVerticalToProfessionCoreMusician(),
            'kpop' => self::getVerticalToProfessionCoreMusician(),
            'rapper\/music' => self::getVerticalToProfessionCoreMusician(),
            'music singer' => self::getVerticalToProfessionCoreMusician(),
            'dj' => self::getVerticalToProfessionCoreMusician(),
            'music band' => self::getVerticalToProfessionCoreMusician(),
            'singer\/artist' => self::getVerticalToProfessionCoreMusician(),
            'singers' => self::getVerticalToProfessionCoreMusician(),
            'singer\/business' => self::getVerticalToProfessionCoreMusician(),
            'singer\/parenting' => self::getVerticalToProfessionCoreMusician(),
            'singer\/songwriter\/actor' => self::getVerticalToProfessionCoreMusician(),
            'voice trainer' => self::getVerticalToProfessionCoreMusician(),

            'director of miss universe malaysia' => self::getVerticalToProfessionCorePageant(),
            'miss' => self::getVerticalToProfessionCorePageant(),
            'miss pageant' => self::getVerticalToProfessionCorePageant(),
            'miss vietnam' => self::getVerticalToProfessionCorePageant(),
            'pageant' => self::getVerticalToProfessionCorePageant(),
            'pageantry' => self::getVerticalToProfessionCorePageant(),
            'missastro' => self::getVerticalToProfessionCorePageant(),
            'missthailandworld' => self::getVerticalToProfessionCorePageant(),
            'missastro' => self::getVerticalToProfessionCorePageant(),
            'miss pageant' => self::getVerticalToProfessionCorePageant(),
            'miss vietnam' => self::getVerticalToProfessionCorePageant(),
            'pageantry' => self::getVerticalToProfessionCorePageant(),
            'director of miss universe malaysia' => self::getVerticalToProfessionCorePageant(),
            'missthailandworld' => self::getVerticalToProfessionCorePageant(),
            'miss' => self::getVerticalToProfessionCorePageant(),

            'videographer' => self::getVerticalToProfessionCorePhotographerVideographer(),
            'photographer' => self::getVerticalToProfessionCorePhotographerVideographer(),
            'photographer' => self::getVerticalToProfessionCorePhotographerVideographer(),

            'doctor' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'medical' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'motivational speaker' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'pilot' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'lawyers' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'lawyer' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'psychologist' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'teacher' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'air stewardess' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'politics' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'medicine' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'public affairs' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'surgery' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelancer' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'brand ambassador' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelance talent' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'ambassador' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'counseling' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'former soldier' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'mentor' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'pharmacist' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'socialite' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'student' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'students' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'tutor' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'sci (1)' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelance' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'sci' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'socialite' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'tutor' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelancer' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'teacher' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'pharmacist' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'air stewardess' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelance' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'ambassador' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'lawyer' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'students' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'personal trainer' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'lawyers' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'mentor' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'student' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'politics' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'doctor' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'figure' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelance talent' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'brand ambassador' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'pilot' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'former soldier' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'freelancer' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'motivational speaker' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'psychologist' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'sci' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'counseling' => self::getVerticalToProfessionCoreProfessionalOccupation(),
            'public affairs' => self::getVerticalToProfessionCoreProfessionalOccupation(),

            'author' => self::getVerticalToProfessionCorePublishing(),
            'comic book artist' => self::getVerticalToProfessionCorePublishing(),
            'journalist' => self::getVerticalToProfessionCorePublishing(),
            'publicer' => self::getVerticalToProfessionCorePublishing(),
            'publisher' => self::getVerticalToProfessionCorePublishing(),
            'writer' => self::getVerticalToProfessionCorePublishing(),
            'writing' => self::getVerticalToProfessionCorePublishing(),
            'magazine' => self::getVerticalToProfessionCorePublishing(),
            'media page\r\nnewspaper' => self::getVerticalToProfessionCorePublishing(),
            'online newspaper' => self::getVerticalToProfessionCorePublishing(),
            'plublisher' => self::getVerticalToProfessionCorePublishing(),
            'plublisher' => self::getVerticalToProfessionCorePublishing(),
            'writer' => self::getVerticalToProfessionCorePublishing(),
            'media page\r\nnewspaper' => self::getVerticalToProfessionCorePublishing(),
            'comic book artist' => self::getVerticalToProfessionCorePublishing(),
            'author' => self::getVerticalToProfessionCorePublishing(),
            'publisher' => self::getVerticalToProfessionCorePublishing(),
            'publicer' => self::getVerticalToProfessionCorePublishing(),
            'journalist' => self::getVerticalToProfessionCorePublishing(),
            'writing' => self::getVerticalToProfessionCorePublishing(),

            'traveler' => self::getVerticalToProfessionCoreTravel(),
            'traveller' => self::getVerticalToProfessionCoreTravel(),
            'travel instagram' => self::getVerticalToProfessionCoreTravel(),
            'guide' => self::getVerticalToProfessionCoreTravel(),
            'tourism' => self::getVerticalToProfessionCoreTravel(),
            'travels' => self::getVerticalToProfessionCoreTravel(),
            'traveler' => self::getVerticalToProfessionCoreTravel(),
            'traveller' => self::getVerticalToProfessionCoreTravel(),
            'travel tv host' => self::getVerticalToProfessionCoreTravel(),
            'tourist' => self::getVerticalToProfessionCoreTravel(),
            'traveling tv host' => self::getVerticalToProfessionCoreTravel(),
            'travel blogger' => self::getVerticalToProfessionCoreTravel(),
            'guide' => self::getVerticalToProfessionCoreTravel(),
            'travel instagram' => self::getVerticalToProfessionCoreTravel(),
            'guide' => self::getVerticalToProfessionCoreTravel(),
            'tourism' => self::getVerticalToProfessionCoreTravel(),
            'travels' => self::getVerticalToProfessionCoreTravel(),
            'traveler' => self::getVerticalToProfessionCoreTravel(),
            'traveller' => self::getVerticalToProfessionCoreTravel(),
            'travel tv host' => self::getVerticalToProfessionCoreTravel(),
            'tourist' => self::getVerticalToProfessionCoreTravel(),
            'traveling tv host' => self::getVerticalToProfessionCoreTravel(),
            'travel blogger' => self::getVerticalToProfessionCoreTravel(),
            'guide' => self::getVerticalToProfessionCoreTravel(),
            'travel instagram' => self::getVerticalToProfessionCoreTravel(),
            'guide' => self::getVerticalToProfessionCoreTravel(),
            'tourism' => self::getVerticalToProfessionCoreTravel(),
            'travels' => self::getVerticalToProfessionCoreTravel(),
            'traveler' => self::getVerticalToProfessionCoreTravel(),
        ];
    }

    private static function getVerticalToProfessionCoreActor()
    {
        return [
            'name' => 'Actor/Actress',
            'description' => '',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreArtist()
    {
        return [
            'name' => 'Artist',
            'description' => 'Any Art related jobs',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreAthelte()
    {
        return [
            'name' => 'Athlete',
            'description' => 'Any Sport related jobs',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreBeauty()
    {
        return [
            'name' => 'Beauty',
            'description' => 'Any Beauty related job (Beauty, Shopping, Fashion & Makeup artist)',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreBusinessFinance()
    {
        return [
            'name' => 'Business & Finance',
            'description' => 'Any Business or Finance related jobs',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreContentCreator()
    {
        return [
            'name' => 'Content Creator',
            'description' => 'Any Media related jobs (Blogger,Iinfluencer, Youtuber, Instagrammer)',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreDesign()
    {
        return [
            'name' => 'Design',
            'description' => 'Any Design or Artwork related jobs',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreDirectorProducer()
    {
        return [
            'name' => 'Director/ Producer',
            'description' => '',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreEntertainer()
    {
        return [
            'name' => 'Entertainer',
            'description' => 'Any Entertainer related jobs (TV host, MC, etc)',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreFoodBeverage()
    {
        return [
            'name' => 'Food & Beverage',
            'description' => 'Any Culinery related jobs',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreGamer()
    {
        return [
            'name' => 'Gamer',
            'description' => '',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreModel()
    {
        return [
            'name' => 'Model',
            'description' => '',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreMusician()
    {
        return [
            'name' => 'Musician',
            'description' => 'Any Music/ Musician related jobs',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCorePageant()
    {
        return [
            'name' => 'Pageant',
            'description' => 'Any Pageant related jobs (Miss universe/country/city pagent winners)',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCorePhotographerVideographer()
    {
        return [
            'name' => 'Photographer / Videographer',
            'description' => '',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreProfessionalOccupation()
    {
        return [
            'name' => 'Professional Occupation',
            'description' => 'Any Commercial related jobs (Doctors, Lawyers, Teacher, etc)',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCorePublishing()
    {
        return [
            'name' => 'Publishing',
            'description' => 'Any Writer related jobs (Author, Journalist, Writer)',
            'type' => 'profession_core',
        ];
    }

    private static function getVerticalToProfessionCoreTravel()
    {
        return [
            'name' => 'Travel',
            'description' => '',
            'type' => 'profession_core',
        ];
    }
}
